### ISSUE TITLE
스크롤 이동중 상단 메뉴가 컨텐츠를 가리거나 메뉴가 보이지 않는 문제 

### ISSUE THREAD

**Issue by insanehong** [playnodeconf/playnode.io-2016#1]
## Case 1.

스크롤을 내리던중 컨텐츠부분과 오버랩 되면서 시야를 어지럽게 하는것 같습니다. 

![play node 2016 - node js conference 0028-11-04 07-48-08](https://cloud.githubusercontent.com/assets/1558742/19988425/576a76c0-a263-11e6-876c-cded5f904962.jpg)

## Case 2.

배경이 하얀색인 곳에서는 메뉴가 보이지 않습니다. 

![play node 2016 - node js conference 0028-11-04 07-48-26](https://cloud.githubusercontent.com/assets/1558742/19988434/631633ba-a263-11e6-8858-45c259ed2fed.jpg)

**Comment by outsideris** [comment]
다 안된거라고 슬랙에 다 썼는데 부들부들... 
이쪽 저장소 아니지만 해결됐으므로 닫습니다.
